### ISSUE TITLE
Weird issue with connection between panel and wings

### ISSUE THREAD

**Issue by NaokiNXN** [EdyTheCow/docker-pterodactyl#29]
Hi

Apologies I can almost 100% guarantee this is a result of me doing something stupid but need help at my wits end with this.

Trying to run this alongside an existing setup so had to modify the traefik labels a bit to fit with my current traefik setup. Got the panel and wings up and for the most part things are working.

However whilst the panel can see wings there seems to be either an issue with wings or the panel im not sure which side has the issue.

On panel I can see the heart showing connecting to wings can be seen as shown in screenshot below:
![1038-245-max](https://user-images.githubusercontent.com/18418986/208542495-c20ec7d2-78eb-44e8-98c1-5a8666f5fae3.png)

But when i go into the node I get the following:

![1035-555-max](https://user-images.githubusercontent.com/18418986/208542547-5fac57cf-6785-4652-b161-a8da54334fda.png)

And if I try to do anything via creating servers or changing any wings settings everything just crashes, i only get a proper error log if I try to make a change to the node settings, I have attached in case it sheds any light on the cause. Again sorry for I can almost guarantee this has been caused by me being stupid somewhere but hopefully someone can help
[Error logs.txt](https://github.com/EdyTheCow/docker-pterodactyl/files/10263370/Error.logs.txt)

**Comment by iproxy** [comment]
Reading the logs, there are lots of permission errors.
Have you set the file permissions? 

`The exception occurred while attempting to log: The stream or file "/app/storage/logs/laravel-2022-12-19.log" could not be opened in append mode: failed to open stream: Permission denied`

Might have to chmod the storage directory 
cd /var/www/pterodactyl/ && chmod -R 755 storage/* bootstrap/cache/
or
Wherever the directory is: /app/storage

**Comment by NaokiNXN** [comment]
Thanks, I did see that issue with permissions but assumed it wasnt the core issue so didn't fix it at the time since figured it would have no impact.

Fixed that but the main issue still remains, heres the logs now:
[pterologs.log](https://github.com/EdyTheCow/docker-pterodactyl/files/10267965/pterologs.log)

Any thoughts?

**Comment by JensenJ** [comment]
Hi there,
I was wondering if you ever found a solution to this?  I have also been running into this intermittent issue for the past year or so and have struggled to find anyone else with this issue. The connection only seems to get lost sometimes, for example when a schedule runs or a power action is sent as you mentioned. Interestingly it seems you can reboot either wings or the panel to fix it until the next interaction with wings. Errors are reported in the logs for wings when the connection is lost but only sometimes show up. 

This could also be caused by a setup where I am running panel and wings on the same computer in the same docker compose file which I know is supposedly not ideal (and this alone could be the issue) but I was wondering if you were also doing the same? To be clear, most of the time the panel and wings work fine in this configuration.

Here is a snippet from my [wings log file](https://github.com/user-attachments/files/16561823/log.txt) showing this issue. If you still have pterodactyl installed do you have this anywhere in your wings.log file?

I also tried using the API to interact with wings but that returned a 500 error when it was in this bad state.

**Comment by NaokiNXN** [comment]
Hi,
No I never found a solution in the end, my use case didn't absolutely require pterodactyl it was just a nice to have so I swtiched to using something else in the end.

Sorry can't help more with this.

**Comment by EdyTheCow** [comment]
I ran into the same issue and never ended up finding a solution, however this is related to specifically wings running under Traefik. This is not an issue related to you running both panel and wings on the same server. All of my tests were done with wings and panel running on separate servers and I've still ended up with the same issue.

The current most simple solution is to not run wings under Traefik, instead you can setup certbot or something similar to generate certificates.

**Comment by JensenJ** [comment]
Glad to know its not something specific to my setup and is instead wings with Traefik. I'll look into this a bit further now I know that its specifically with Traefik and not caused by Docker or some other combination of things. 
Thank you very much.

**Comment by JensenJ** [comment]
Hi there.
I seem to have found something which may have fixed this and am posting this for anyone else running into the issue.  I haven't had the issue now (or haven't noticed it) for about two weeks with this, so that's great. 
It seems by reducing the HTTP connection and request timeout in admin settings on the panel resolves the issue, or at least mitigates it. For reference, I changed the value to 3 seconds for both, from the default of (I think) 30. I am not knowledgeable enough to say why this may fix it but my best guess would be Traefik sending a request or something to the panel/wings which takes forever to time out, giving the appearance of it being frozen/disconnected? 

These settings are located under Admin->Settings->Advanced. Hope this helps someone.

**Comment by EdyTheCow** [comment]
Thanks for posting your findings. This is exactly what I suspected the issue was but had no idea why. Let me know how it goes after awhile!
